config/routes.rb
Hub51::Application.routes.draw do
  root 'selections#index'

  get '/restrictions/new', controller: 'restrictions', action: 'new', as: 'new_restriction'
  post '/restrictions', controller: 'restrictions', action: 'create', as: 'restrictions'

  get '/restrictions', controller: 'restrictions', action: 'index'
  get '/restrictions/:id', controller: 'restrictions', action: 'show', as: 'restriction'

  get '/restrictions/:id/edit', controller: 'restrictions', action: 'edit', as: 'edit_restriction'
  patch '/restrictions/:id', controller: 'restrictions', action: 'update'

  delete '/restrictions/:id', controller: 'restrictions', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/selections/new', controller: 'selections', action: 'new', as: 'new_selection'
  post '/selections', controller: 'selections', action: 'create', as: 'selections'

  get '/selections', controller: 'selections', action: 'index'
  get '/selections/:id', controller: 'selections', action: 'show', as: 'selection'

  get '/selections/:id/edit', controller: 'selections', action: 'edit', as: 'edit_selection'
  patch '/selections/:id', controller: 'selections', action: 'update'

  delete '/selections/:id', controller: 'selections', action: 'destroy'

  get '/entrees/new', controller: 'entrees', action: 'new', as: 'new_entree'
  post '/entrees', controller: 'entrees', action: 'create', as: 'entrees'

  get '/entrees', controller: 'entrees', action: 'index'
  get '/entrees/:id', controller: 'entrees', action: 'show', as: 'entree'

  get '/entrees/:id/edit', controller: 'entrees', action: 'edit', as: 'edit_entree'
  patch '/entrees/:id', controller: 'entrees', action: 'update'

  delete '/entrees/:id', controller: 'entrees', action: 'destroy'

  get '/starters/new', controller: 'starters', action: 'new', as: 'new_starter'
  post '/starters', controller: 'starters', action: 'create', as: 'starters'

  get '/starters', controller: 'starters', action: 'index'
  get '/starters/:id', controller: 'starters', action: 'show', as: 'starter'

  get '/starters/:id/edit', controller: 'starters', action: 'edit', as: 'edit_starter'
  patch '/starters/:id', controller: 'starters', action: 'update'

  delete '/starters/:id', controller: 'starters', action: 'destroy'

end

app/models/restriction.rb
class Restriction < ActiveRecord::Base
  belongs_to :starter
  belongs_to :entree
end

app/controllers/restrictions_controller.rb
class RestrictionsController < ApplicationController

  def index
    @restrictions = Restriction.all
  end

  def show
    @restriction = Restriction.find_by(id: params[:id])
  end

  def new
  end

  def create
    @restriction = Restriction.new
    @restriction.starter_id = params[:starter_id]
    @restriction.entree_id = params[:entree_id]

    if @restriction.save
      redirect_to restrictions_url, notice: "Restriction created successfully."
    else
      render 'new'
    end
  end

  def edit
    @restriction = Restriction.find_by(id: params[:id])
  end

  def update
    @restriction = Restriction.find_by(id: params[:id])
    @restriction.starter_id = params[:starter_id]
    @restriction.entree_id = params[:entree_id]

    if @restriction.save
      redirect_to restrictions_url, notice: "Restriction updated successfully."
    else
      render 'new'
    end
  end

  def destroy
    @restriction = Restriction.find_by(id: params[:id])
    @restriction.destroy

    redirect_to restrictions_url, notice: "Restriction deleted."
  end
end

app/views/restrictions/edit.html.erb
<div class="page-header">
  <h1>Editing Restriction #<%= @restriction.id %></h1>
</div>

<%= form_tag(restriction_url(@restriction), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :starter_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :starter_id, @restriction.starter_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :entree_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :entree_id, @restriction.entree_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Restriction", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/restrictions/index.html.erb
<div class="page-header">
  <h1>Restrictions</h1>
</div>

<p><%= link_to 'Add a New Restriction', new_restriction_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Starter</th>
      <th>Entree</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restrictions.each do |restriction| %>
      <tr>
        <td><%= restriction.starter_id %></td>
        <td><%= restriction.entree_id %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, restriction_url(restriction), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_restriction_url(restriction), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, restriction_url(restriction), method: 'delete', data: { confirm: "Do you really want to delete this restriction?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restrictions/new.html.erb
<div class="page-header">
  <h1>New Restriction</h1>
</div>

<%= form_tag(restrictions_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :starter_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :starter_id, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :entree_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :entree_id, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Restriction", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/restrictions/show.html.erb
<div class="page-header">
  <h1>Restriction #<%= @restriction.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Starter</dt>
  <dd><%= @restriction.starter_id %></dd>

  <dt>Entree</dt>
  <dd><%= @restriction.entree_id %></dd>

</dl>