config/routes.rb
Hub51::Application.routes.draw do
  root 'selections#index'

  get '/restrictions/new', controller: 'restrictions', action: 'new', as: 'new_restriction'
  post '/restrictions', controller: 'restrictions', action: 'create', as: 'restrictions'

  get '/restrictions', controller: 'restrictions', action: 'index'
  get '/restrictions/:id', controller: 'restrictions', action: 'show', as: 'restriction'

  get '/restrictions/:id/edit', controller: 'restrictions', action: 'edit', as: 'edit_restriction'
  patch '/restrictions/:id', controller: 'restrictions', action: 'update'

  delete '/restrictions/:id', controller: 'restrictions', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/selections/new', controller: 'selections', action: 'new', as: 'new_selection'
  post '/selections', controller: 'selections', action: 'create', as: 'selections'

  get '/selections', controller: 'selections', action: 'index'
  get '/selections/:id', controller: 'selections', action: 'show', as: 'selection'

  get '/selections/:id/edit', controller: 'selections', action: 'edit', as: 'edit_selection'
  patch '/selections/:id', controller: 'selections', action: 'update'

  delete '/selections/:id', controller: 'selections', action: 'destroy'

  get '/entrees/new', controller: 'entrees', action: 'new', as: 'new_entree'
  post '/entrees', controller: 'entrees', action: 'create', as: 'entrees'

  get '/entrees', controller: 'entrees', action: 'index'
  get '/entrees/:id', controller: 'entrees', action: 'show', as: 'entree'

  get '/entrees/:id/edit', controller: 'entrees', action: 'edit', as: 'edit_entree'
  patch '/entrees/:id', controller: 'entrees', action: 'update'

  delete '/entrees/:id', controller: 'entrees', action: 'destroy'

  get '/starters/new', controller: 'starters', action: 'new', as: 'new_starter'
  post '/starters', controller: 'starters', action: 'create', as: 'starters'

  get '/starters', controller: 'starters', action: 'index'
  get '/starters/:id', controller: 'starters', action: 'show', as: 'starter'

  get '/starters/:id/edit', controller: 'starters', action: 'edit', as: 'edit_starter'
  patch '/starters/:id', controller: 'starters', action: 'update'

  delete '/starters/:id', controller: 'starters', action: 'destroy'

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :first_starter, class_name: "Starter"
  belongs_to :second_starter, class_name: "Starter"
  belongs_to :first_entree, class_name: "Entree"
  belongs_to :second_entree, class_name: "Entree"

  validates :diner, presence: true, uniqueness: true
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController

  def index
    @selections = Selection.all
  end

  def show
    @selection = Selection.find_by(id: params[:id])
  end

  def new
    @selection = Selection.new
  end

  def create
    @selection = Selection.new
    @selection.diner = params[:diner]
    @selection.first_starter_id = params[:first_starter_id]
    @selection.second_starter_id = params[:second_starter_id]
    @selection.first_entree_id = params[:first_entree_id]
    @selection.second_entree_id = params[:second_entree_id]
    @selection.comments = params[:comments]

    if @selection.save
      redirect_to selections_url, notice: "Selection created successfully."
    else
      render 'new'
    end
  end

  def edit
    @selection = Selection.find_by(id: params[:id])
  end

  def update
    @selection = Selection.find_by(id: params[:id])
    @selection.diner = params[:diner]
    @selection.first_starter_id = params[:first_starter_id]
    @selection.second_starter_id = params[:second_starter_id]
    @selection.first_entree_id = params[:first_entree_id]
    @selection.second_entree_id = params[:second_entree_id]
    @selection.comments = params[:comments]

    if @selection.save
      redirect_to selections_url, notice: "Selection updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @selection = Selection.find_by(id: params[:id])
    @selection.destroy

    redirect_to selections_url, notice: "Selection deleted."
  end
end

app/views/selections/edit.html.erb
<div class="page-header">
  <h1>Editing Selection #<%= @selection.id %></h1>
</div>

<% if @selection.errors.any? %>
  <% @selection.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(selection_url(@selection), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :diner, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :diner, @selection.diner, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :first_starter_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :first_starter_id, option_groups_from_collection_for_select(Category.all, :starters, :name, :id, :name, @selection.first_starter_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :second_starter_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :second_starter_id, option_groups_from_collection_for_select(Category.all, :starters, :name, :id, :name, @selection.second_starter_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :first_entree_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :first_entree_id, option_groups_from_collection_for_select(Category.all, :entrees, :name, :id, :name, @selection.first_entree_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :second_entree_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :second_entree_id, option_groups_from_collection_for_select(Category.all, :entrees, :name, :id, :name, @selection.second_entree_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :comments, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :comments, @selection.comments, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Selection", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/selections/index.html.erb
<div class="page-header">
  <h1>Selections</h1>
</div>

<p><%= link_to 'Add a New Selection', new_selection_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Diner</th>
      <th>First starter</th>
      <th>Second starter</th>
      <th>First entree</th>
      <th>Second entree</th>
      <th>Comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.diner %></td>
        <td><%= selection.first_starter.name %></td>
        <td><%= selection.second_starter.name %></td>
        <td><%= selection.first_entree.name %></td>
        <td><%= selection.second_entree.name %></td>
        <td><%= selection.comments %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, selection_url(selection), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_selection_url(selection), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, selection_url(selection), method: 'delete', data: { confirm: "Do you really want to delete this selection?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/selections/new.html.erb
<div class="page-header">
  <h1>New Selection</h1>
</div>

<% if @selection.errors.any? %>
  <% @selection.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_tag(selections_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :diner, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :diner, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :first_starter_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :first_starter_id, option_groups_from_collection_for_select(Category.all, :starters, :name, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :second_starter_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :second_starter_id, option_groups_from_collection_for_select(Category.all, :starters, :name, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :first_entree_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :first_entree_id, option_groups_from_collection_for_select(Category.all, :entrees, :name, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :second_entree_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :second_entree_id, option_groups_from_collection_for_select(Category.all, :entrees, :name, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :comments, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :comments, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Selection", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/selections/show.html.erb
<div class="page-header">
  <h1>Selection #<%= @selection.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Diner</dt>
  <dd><%= @selection.diner %></dd>

  <dt>First starter</dt>
  <dd><%= @selection.first_starter.name %></dd>

  <dt>Second starter</dt>
  <dd><%= @selection.second_starter.name %></dd>

  <dt>First entree</dt>
  <dd><%= @selection.first_entree.name %></dd>

  <dt>Second entree</dt>
  <dd><%= @selection.second_entree.name %></dd>

  <dt>Comments</dt>
  <dd><%= @selection.comments %></dd>

</dl>